# Generated by Django 4.2 on 2023-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True, verbose_name='ایمیل'),
        ),
    ]
