# Generated by Django 4.2 on 2023-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0002_alter_normal_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='آدرس محل سکونت'),
        ),
        migrations.AddField(
            model_name='normal_user',
            name='city',
            field=models.CharField(blank=True, choices=[('mashhad', 'مشهد'), ('tehran', 'تهران'), ('shiraz', 'شیراز'), ('isfahan', 'اصهان'), ('rasht', 'رشت'), ('sarry', 'ساری'), ('az', 'یزد'), ('mashhad', 'کرمان')], max_length=20, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='normal_user',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='normal_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='normal_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام'),
        ),
    ]
