# Generated by Django 4.2 on 2023-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0003_normal_user_address_normal_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
