# Generated by Django 4.2 on 2023-07-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0004_alter_normal_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='تصویر پروفایل'),
        ),
    ]
