# Generated by Django 4.2 on 2023-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0005_normal_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='reset_password_code',
            field=models.CharField(default='', max_length=100, verbose_name='کد تغییر رمز عبور'),
        ),
    ]
