# Generated by Django 4.2 on 2023-11-28 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0006_normal_user_reset_password_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300, null=True, verbose_name='message')),
                ('reciever_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام به کاربرها',
                'verbose_name_plural': 'پیام ها به کاربرها',
            },
        ),
    ]
