# Generated by Django 4.2 on 2023-12-08 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0007_user_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_messages',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد پیام'),
        ),
        migrations.AlterField(
            model_name='user_messages',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='user_messages',
            name='reciever_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت کننده پیام'),
        ),
    ]
