# Generated by Django 4.2 on 2023-12-15 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='کالا')),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران علاقه مند به این کالا')),
            ],
            options={
                'verbose_name': 'علاقه مندی کالا',
                'verbose_name_plural': 'علاقه مندی های کالا ها',
            },
        ),
    ]
